# Generated by Django 4.2 on 2025-12-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_remove_client_address_remove_client_company_and_more"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="service_info", name="information",),
        migrations.CreateModel(
            name="CustomServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="services/")),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "selected_services",
                    models.ManyToManyField(to="services.service_info"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="services/images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.customservicerequest",
                    ),
                ),
            ],
        ),
    ]
