# Generated by Django 4.2 on 2025-12-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0002_remove_service_info_information_customservicerequest_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="service_info",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_info",
                to="services.service",
            ),
        ),
    ]
