# Generated by Django 4.2 on 2025-12-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_info_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="customservicerequest", name="image",),
    ]
