# Generated by Django 4.2 on 2026-01-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_remove_customservicerequest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customservicerequest",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
