# Generated by Django 4.2 on 2026-01-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_customservicerequest_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customservicerequest",
            name="admin_status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AddField(
            model_name="customservicerequest",
            name="pm_status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
