# Generated by Django 4.2 on 2026-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqchatmessage",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("admin_client", "Admin ↔ Client"),
                    ("admin_pm", "Admin ↔ Project Manager"),
                ],
                default="ADMIN_CLIENT",
                max_length=20,
            ),
        ),
    ]
