# Generated by Django 4.2 on 2026-01-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subvendors", "0001_initial"),
        ("chat", "0002_rfqchatmessage_chat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqchatmessage",
            name="receiver_subvendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="subvendors.subvendor",
            ),
        ),
        migrations.AlterField(
            model_name="rfqchatmessage",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("admin_client", "Admin ↔ Client"),
                    ("admin_pm", "Admin ↔ Project Manager"),
                    ("pm_subvendor", "PM ↔ SubVendor"),
                ],
                default="ADMIN_CLIENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rfqchatmessage",
            name="sender_role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("project_manager", "Project Manager"),
                    ("subvendor", "SubVendor"),
                ],
                max_length=20,
            ),
        ),
    ]
