# Generated by Django 4.2 on 2026-01-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deliverables", "0004_deliverable_status_and_more"),
        ("chat", "0003_rfqchatmessage_receiver_subvendor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfqchatmessage",
            name="deliverable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="deliverables.deliverable",
            ),
        ),
    ]
