# Generated by Django 4.2 on 2025-12-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("clients", "0004_alter_client_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="accounts.company",
            ),
        ),
    ]
