# Generated by Django 4.2 on 2025-12-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_client_company"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="address",),
        migrations.RemoveField(model_name="client", name="company",),
        migrations.AddField(
            model_name="client", name="country", field=models.CharField(blank=True),
        ),
    ]
