# Generated by Django 4.2 on 2026-01-07 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_managers", "0001_initial"),
        ("clients", "0007_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rfqs",
                to="project_managers.projectmanager",
            ),
        ),
    ]
