# Generated by Django 4.2 on 2026-01-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_client_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="assigned_to",),
    ]
