# Generated by Django 4.2 on 2026-01-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deliverables", "0002_alter_deliverable_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="deliverable", name="attachment",),
        migrations.CreateModel(
            name="DeliverableAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="deliverables/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="deliverables.deliverable",
                    ),
                ),
            ],
        ),
    ]
