# Generated by Django 4.2 on 2026-01-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deliverables", "0003_remove_deliverable_attachment_deliverableattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="status",
            field=models.CharField(default="Assigned", max_length=50),
        ),
        migrations.AlterField(
            model_name="deliverableattachment",
            name="deliverable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment",
                to="deliverables.deliverable",
            ),
        ),
    ]
